POST http://localhost:4000/api/blogs/
Content-Type: application/json

{
    "title": "New Api Test",
    "author": "Dan Jenkins",
    "url": "https://danapipatterns.com/",
    "likes": 16,
    "userId" : "67e347127ac56d4f5233d671"
}

###

GET http://localhost:4000/api/blogs/

###

GET  http://localhost:4000/api/blogs/67d2db44eae080182178f625

###
POST http://localhost:4000/api/users/
Content-Type: application/json

{
    "username" : "fyfy",
    "name" : "Ifeanyi Omeje",
    "password" : "19041997"

}

###
GET http://localhost:4000/api/users/