POST http://localhost:4000/api/blogs/
Content-Type: application/json

{
    "title": "React patterns",
    "author": "Michael Chan",
    "url": "https://reactpatterns.com/",
    "likes": 7
}

###

GET http://localhost:4000/api/blogs/