const anecdotes = [
    "The best way to predict the future is to invent it.",
    "Simplicity is the ultimate sophistication.",
    "First, solve the problem. Then, write the code.",
    "Good code is its own best documentation.",
    "Programs must be written for people to read, and only incidentally for machines to execute.",
    "Simplicity is the soul of efficiency.",
    "Premature optimization is the root of all evil.",
    "Make it work, make it right, make it fast.",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.",
    "Code never lies, comments sometimes do.",
    "The best error message is the one that never shows up.",
    "If debugging is the process of removing software bugs, then programming must be the process of putting them in.",
    "A user interface is like a joke. If you have to explain it, it’s not that good.",
    "Experience is the name everyone gives to their mistakes.",
    "It works on my machine!",
    "Programming is thinking, not typing.",
    "Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday’s code.",
    "It's not a bug – it's an undocumented feature.",
    "The code is not the product; the product is the product.",
    "The most disastrous thing you can do is to believe that you are working for the person who pays you rather than for the customer.",
    "Testing leads to failure, and failure leads to understanding.",
    "Optimism is an occupational hazard of programming: feedback is the treatment.",
    "Walking on water and developing software from a specification are easy if both are frozen.",
    "The best way to get a project done faster is to start sooner.",
    "Software is like entropy: It is difficult to grasp, weighs nothing, and obeys the second law of thermodynamics; i.e., it always increases.",
    "Weeks of coding can save you hours of planning.",
    "A good programmer is someone who always looks both ways before crossing a one-way street.",
    "The only way to learn a new programming language is by writing programs in it.",
    "A program is never less than 90% complete, and never more than 95% complete.",
    "Deleted code is debugged code.",
    "The best thing about a boolean is even if you are wrong, you are only off by a bit.",
    "You can’t have great software without a great team, and most software teams behave like dysfunctional families.",
    "Without requirements or design, programming is the art of adding bugs to an empty text file.",
    "Programming can be fun, so can cryptography; however, they should not be combined.",
    "If the code and the comments disagree, then both are probably wrong.",
    "In theory, theory and practice are the same. In practice, they’re not.",
    "One man’s crappy software is another man’s full-time job.",
    "A language that doesn’t affect the way you think about programming is not worth knowing.",
    "The cheapest, fastest, and most reliable components are those that aren’t there.",
    "The trouble with programmers is that you can never tell what a programmer is doing until it’s too late.",
    "Most software isn’t designed. Most software is simply evolved.",
    "Software undergoes beta testing shortly before it’s released. Beta is Latin for 'still doesn’t work.'",
    "The function of good software is to make the complex appear simple.",
    "Programming today is a race between software engineers striving to build bigger and better idiot-proof programs, and the universe trying to produce bigger and better idiots. So far, the universe is winning.",
    "If builders built buildings the way programmers wrote programs, then the first woodpecker that came along would destroy civilization.",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight.",
    "Code is like humor. When you have to explain it, it’s bad.",
    "If you think it's simple, then you have misunderstood the problem.",
    "You should name a variable using the same care with which you name a first-born child.",
    "Every great developer you know got there by solving problems they were unqualified to solve until they actually did it.",
    "The best performance improvement is the transition from the nonworking state to the working state.",
    "A primary cause of complexity is that software vendors uncritically adopt almost any feature that users want.",
    "Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.",
    "A good programmer is someone who looks both ways before crossing a one-way street.",
    "You can’t trust code that you did not totally create yourself.",
    "Programming isn’t about what you know; it’s about what you can figure out.",
    "A code review is the process of pretending to work while actually reading someone else’s code.",
    "Hardware eventually fails. Software eventually works.",
    "Before software can be reusable, it first has to be usable.",
    "Make things as simple as possible, but not simpler.",
    "People don’t care about how much you know until they know how much you care."
  ];
  

export default anecdotes;