DELETE http://localhost:3063/api/contacts/67a365237d84c5d6d79daf6d

###
POST http://localhost:3063/api/contacts/
Content-Type: application/json

{
    "name"  : "john",
    "number" : "1434567876"
}

###
GET  http://localhost:3063/api/contacts/

###
GET http://localhost:3063/api/contacts/

