DELETE http://localhost:3063/api/contacts/1

###
POST http://localhost:3063/api/contacts/
Content-Type: application/json

{
    "name"  : "Mathew Louie",
    "number" : "09083931094"
}

###
GET  http://localhost:3063/api/contacts/

###
GET http://localhost:3063/api/contacts/

